DROP TABLE IF EXISTS ACCOUNTS;
DROP TABLE IF EXISTS CART;
DROP TABLE IF EXISTS PURCHASES;
DROP TABLE IF EXISTS LOCATIONS;
DROP TABLE IF EXISTS COUPONS;

DROP USER 'shinetheweb'@'localhost';

DROP DATABASE IF EXISTS SUNSHINEDEALS;
DROP DATABASE IF EXISTS sunshinedeals;
