DROP DATABASE IF EXISTS SUNSHINEDEALS;
DROP DATABASE IF EXISTS sunshinedeals;

CREATE DATABASE SUNSHINEDEALS;
CREATE USER 'shinetheweb'@'localhost' IDENTIFIED BY 'urmysunshine';

USE SUNSHINEDEALS;
GRANT ALL ON SUNSHINEDEALS.* TO 'shinetheweb'@'localhost';

DROP TABLE IF EXISTS ACCOUNTS;
DROP TABLE IF EXISTS CART;
DROP TABLE IF EXISTS PURCHASES;
DROP TABLE IF EXISTS LOCATIONS;
DROP TABLE IF EXISTS COUPONS;

CREATE TABLE LOCATIONS (
	LOC_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	LOC_NAME VARCHAR(30),
	LOC_STATE CHAR(2),
	LOC_ZIP INT
);

CREATE TABLE ACCOUNTS (
	ACCT_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ACCT_NAME VARCHAR(30),
	ACCT_PASS varchar(40),
	ACCT_EMAIL varchar(32),
	ACCT_SQUEST varchar(100),
	ACCT_SANSER varchar(100),
	ACCT_JOIN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ACCT_LOC INT
);

CREATE TABLE COUPONS (
	COUP_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	COUP_NAME varchar(30),
	COUP_TOTAL INT,
	COUP_LEFT INT,
	COUP_PRICE DECIMAL(6,2),
	COUP_CATNAME VARCHAR(20),
	COUP_VENDOR VARCHAR(30),
	COUP_DESC VARCHAR(1000),
	COUP_START TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	COUP_EXPR TIMESTAMP
);

CREATE TABLE CART (
	CART_ID INT NOT NULL,
	CART_ACCT_ID INT NOT NULL,
	CART_COUP_ID INT NOT NULL,
	CART_NUMB INT,
	CART_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PURCHASES (
	PUR_ID INT NOT NULL,
	PUR_ACCT_ID INT NOT NULL,
	PUR_COUP_ID INT NOT NULL,
	PUR_NUMB INT,
	PUR_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX LOC_INDEX ON LOCATIONS(LOC_ID ASC);
CREATE UNIQUE INDEX ACCT_INDEX ON ACCOUNTS(ACCT_ID ASC);
CREATE UNIQUE INDEX COUP_INDEX ON COUPONS(COUP_ID ASC);
CREATE INDEX CART_INDEX ON CART(CART_ID ASC);
CREATE INDEX PUR_INDEX ON PURCHASES(PUR_ID ASC);

ALTER TABLE ACCOUNTS ADD CONSTRAINT ACCTFK_LOC FOREIGN KEY(ACCT_LOC) REFERENCES LOCATIONS(LOC_ID);
ALTER TABLE CART ADD CONSTRAINT CARTFK_ACCT FOREIGN KEY(CART_ACCT_ID) REFERENCES ACCOUNTS(ACCT_ID);
ALTER TABLE CART ADD CONSTRAINT CARTFK_COUP FOREIGN KEY(CART_COUP_ID) REFERENCES COUPONS(COUP_ID);
ALTER TABLE PURCHASES ADD CONSTRAINT PURFK_ACCT FOREIGN KEY(PUR_ACCT_ID) REFERENCES ACCOUNTS(ACCT_ID);
ALTER TABLE PURCHASES ADD CONSTRAINT PURFK_COUP FOREIGN KEY(PUR_COUP_ID) REFERENCES COUPOUNS(COUP_ID);

INSERT INTO LOCATIONS (LOC_NAME, LOC_STATE, LOC_ZIP) VALUES ('Union City','CA',94587);
INSERT INTO LOCATIONS (LOC_NAME, LOC_STATE, LOC_ZIP) VALUES ('Fremont','CA',94536);
INSERT INTO LOCATIONS (LOC_NAME, LOC_STATE, LOC_ZIP) VALUES ('Santa Clara','CA',95192);

INSERT INTO ACCOUNTS (ACCT_NAME, ACCT_PASS, ACCT_EMAIL, ACCT_SQUEST, ACCT_SANSER, ACCT_LOC) VALUES ('Bob',SHA1(MD5('magic133')), 'bob@se133.com', 'Who is your best friend?', SHA1(MD5('Google')), 1);
INSERT INTO ACCOUNTS (ACCT_NAME, ACCT_PASS, ACCT_EMAIL, ACCT_SQUEST, ACCT_SANSER, ACCT_LOC) VALUES ('Joe',SHA1(MD5('magic133')), 'joe@se133.com', 'Who is your best friend?', SHA1(MD5('Jane')), 2);
INSERT INTO ACCOUNTS (ACCT_NAME, ACCT_PASS, ACCT_EMAIL, ACCT_SQUEST, ACCT_SANSER, ACCT_LOC) VALUES ('Jane',SHA1(MD5('magic133')), 'jane@se133.com', 'Who is your best friend?', SHA1(MD5('Joe')), 2);
INSERT INTO ACCOUNTS (ACCT_NAME, ACCT_PASS, ACCT_EMAIL, ACCT_SQUEST, ACCT_SANSER, ACCT_LOC) VALUES ('Zelda',SHA1(MD5('magic133')), 'zelda@se133.com', 'Who is your best friend?', SHA1(MD5('No one')), 3);

INSERT INTO COUPONS (COUP_NAME, COUP_TOTAL, COUP_LEFT, COUP_PRICE, COUP_CATNAME, COUP_VENDOR, COUP_DESC, COUP_EXPR) VALUES ('Car Part',10,10,49.99,'Automotive','Vendor 1','Coupon desc goes here: It does something to someone that makes someone else happy or at least that someone hopes so!', '2012-05-30 23:59:59');
INSERT INTO COUPONS (COUP_NAME, COUP_TOTAL, COUP_LEFT, COUP_PRICE, COUP_CATNAME, COUP_VENDOR, COUP_DESC, COUP_EXPR) VALUES ('Baby Stuff',10,10,49.99,'Family Care','Vendor 2','Coupon desc goes here: It does something to someone that makes someone else happy or at least that someone hopes so!', '2012-05-30 23:59:59');
INSERT INTO COUPONS (COUP_NAME, COUP_TOTAL, COUP_LEFT, COUP_PRICE, COUP_CATNAME, COUP_VENDOR, COUP_DESC, COUP_EXPR) VALUES ('Travel Abroad',10,10,49.99,'Travel','Vendor 3','Coupon desc goes here: It does something to someone that makes someone else happy or at least that someone hopes so!', '2012-05-30 23:59:59');
INSERT INTO COUPONS (COUP_NAME, COUP_TOTAL, COUP_LEFT, COUP_PRICE, COUP_CATNAME, COUP_VENDOR, COUP_DESC, COUP_EXPR) VALUES ('Spicy Food Thingy',10,10,49.99,'Food','Vendor 4','Coupon desc goes here: It does something to someone that makes someone else happy or at least that someone hopes so!', '2012-05-30 23:59:59');
INSERT INTO COUPONS (COUP_NAME, COUP_TOTAL, COUP_LEFT, COUP_PRICE, COUP_CATNAME, COUP_VENDOR, COUP_DESC, COUP_EXPR) VALUES ('Sofas',10,10,49.99,'Living','Vendor 5','Coupon desc goes here: It does something to someone that makes someone else happy or at least that someone hopes so!', '2012-05-30 23:59:59');

INSERT INTO CART (CART_ID, CART_ACCT_ID, CART_COUP_ID, CART_NUMB) VALUES (0,1,3,4);
INSERT INTO CART (CART_ID, CART_ACCT_ID, CART_COUP_ID, CART_NUMB) VALUES (0,1,1,3);
INSERT INTO CART (CART_ID, CART_ACCT_ID, CART_COUP_ID, CART_NUMB) VALUES (1,2,1,2);
INSERT INTO CART (CART_ID, CART_ACCT_ID, CART_COUP_ID, CART_NUMB) VALUES (1,2,5,2);
INSERT INTO CART (CART_ID, CART_ACCT_ID, CART_COUP_ID, CART_NUMB) VALUES (2,3,2,6);
